<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
	<NoWarn>$(NoWarn);1591</NoWarn>
	<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Transacciones.Core-6bbcbd88-7541-43e3-bb73-3d1bae45604d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.Specification" Version="9.0.1" />
    <PackageReference Include="Ardalis.Specification.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Entities\CuentaAggregate\Specification\" />
    <Folder Include="Entities\TransaccionAggregate\Specification\" />
    <Folder Include="Interfaces\" />
  </ItemGroup>
</Project>
